package br.com.grace.view;

import br.com.grace.model.Estudante;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import br.com.grace.dao.DisciplinaDao;
import br.com.grace.model.Disciplina;

public class DisciplinaView extends javax.swing.JInternalFrame {

    Estudante estudante;
    HomeView funcoes;

    public HomeView getFuncoes() {
        return funcoes;
    }

    public void setFuncoes(HomeView funcoes) {
        this.funcoes = funcoes;
    }

    public Estudante getEstudante() {
        return estudante;
    }

    public void setEstudante(Estudante estudante) {
        this.estudante = estudante;
    }

    /**
     * Creates new form Disciplina
     */
    public DisciplinaView() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroDisciplina.getModel();
        jTableCadastroDisciplina.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroDisciplina.getModel();
        modelo.setNumRows(0);
        DisciplinaDao mdao = new DisciplinaDao();

        for (Disciplina m : mdao.read()) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNome(),
                m.getAssunto()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroDisciplina = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de disciplina");

        jLabel1.setText("Nome:");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jTableCadastroDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Assunto", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCadastroDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroDisciplinaMouseClicked(evt);
            }
        });
        jTableCadastroDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCadastroDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroDisciplina);

        jLabel3.setText("Id:");

        jTextFieldId.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addGap(47, 47, 47)
                                .addComponent(jButtonCadastrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizar)
                        .addGap(102, 102, 102)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableCadastroDisciplina.getSelectedRow() != -1) {

            Disciplina m = new Disciplina("", "");
            DisciplinaDao dao = new DisciplinaDao();

            m.setId((int) jTableCadastroDisciplina.getValueAt(jTableCadastroDisciplina.getSelectedRow(), 0));
            dao.delete(m);
            readJTable();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if (jTableCadastroDisciplina.getSelectedRow() != -1) {
            jTableCadastroDisciplina.setValueAt(jTextFieldNome.getText(), jTableCadastroDisciplina.getSelectedRow(), 0);

            Disciplina m = new Disciplina("", "");
            DisciplinaDao dao = new DisciplinaDao();

            m.setNome(jTextFieldNome.getText());
            m.setId(Integer.parseInt(jTextFieldId.getText()));
            dao.update(m);

            readJTable();
        } else {
            JOptionPane.showMessageDialog(this, "selecione uma linha para atualizar");
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        String nome = jTextFieldNome.getText();
        Disciplina m = new Disciplina(nome, "");

        DisciplinaDao md = new DisciplinaDao();
        md.create(m);
        readJTable();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTableCadastroDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCadastroDisciplinaKeyReleased
        if (jTableCadastroDisciplina.getSelectedRow() != -1) {
            jTextFieldId.setText(jTableCadastroDisciplina.getValueAt(jTableCadastroDisciplina.getSelectedRow(), 0).toString());
            jTextFieldNome.setText(jTableCadastroDisciplina.getValueAt(jTableCadastroDisciplina.getSelectedRow(), 1).toString());
         
        }
    }//GEN-LAST:event_jTableCadastroDisciplinaKeyReleased

    private void jTableCadastroDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroDisciplinaMouseClicked
        if (jTableCadastroDisciplina.getSelectedRow() != -1) {
            jTextFieldId.setText(jTableCadastroDisciplina.getValueAt(jTableCadastroDisciplina.getSelectedRow(), 0).toString());
            jTextFieldNome.setText(jTableCadastroDisciplina.getValueAt(jTableCadastroDisciplina.getSelectedRow(), 1).toString());
           
        }
    }//GEN-LAST:event_jTableCadastroDisciplinaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroDisciplina;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
