package br.com.grace.view;

import br.com.grace.model.Estudante;
import br.com.grace.model.Disciplina;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.grace.dao.EventoDao;
import br.com.grace.dao.DisciplinaDao;
import br.com.grace.model.Evento;

public class EventoView extends javax.swing.JInternalFrame {

    Estudante estudante;
    HomeView funcoes;

    public HomeView getFuncoes() {
        return funcoes;
    }

    public void setFuncoes(HomeView funcoes) {
        this.funcoes = funcoes;
    }

    public Estudante getEstudante() {
        return estudante;
    }

    public void setEstudante(Estudante estudante) {
        this.estudante = estudante;
    }

    /**
     * Creates new form Evento
     */
    public EventoView() {
        initComponents();
        readJTable();
        DisciplinaDao dd = new DisciplinaDao();

        for (Disciplina d : dd.read()) {
            jComboBoxDisciplina.addItem(d);
        }
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroEvento.getModel();
        modelo.setNumRows(0);
        EventoDao fdao = new EventoDao();

        for (Evento f : fdao.read()) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getTipo(),
                f.getNome(),
                f.getData(),
                f.getHora(),
                f.getIdDisciplina(),
                f.getFrequencia(),
                f.getStatus(),
                f.getAssunto()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldHora = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxFrequencia = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxDisciplina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroEvento = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAssunto = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Eventos");
        setToolTipText("");

        jLabel1.setText("Tipo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Data:");

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Hora:");

        try {
            jFormattedTextFieldHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Disciplina:");

        jLabel6.setText("Frequência:");

        jComboBoxFrequencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Semanalmente", "Mensalmente", "Anualmente" }));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Status:");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluído", "Em progresso", " " }));

        jComboBoxDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDisciplinaActionPerformed(evt);
            }
        });

        jTableCadastroEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Nome", "Data", "Hora", "Disciplina", "Frequência", "Status", "Assunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCadastroEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroEventoMouseClicked(evt);
            }
        });
        jTableCadastroEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCadastroEventoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroEvento);

        jLabel8.setText("Id:");

        jTextFieldId.setEditable(false);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoal", "Escolar" }));

        jLabel9.setText("Assunto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButtonCadastrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jButtonAtualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jFormattedTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        String tipo = (String) jComboBoxTipo.getSelectedItem();
        String nome = jTextFieldNome.getText();
        String data = jFormattedTextFieldData.getText();
        String hora = jFormattedTextFieldHora.getText();
        String frequencia = (String) jComboBoxFrequencia.getSelectedItem();
        String status = (String) jComboBoxStatus.getSelectedItem();
        String assunto = jTextFieldAssunto.getText();

        Disciplina disciplina = (Disciplina) jComboBoxDisciplina.getSelectedItem();

        Evento f = new Evento(tipo, nome, data, hora, disciplina.getId(), frequencia, status, assunto);

        EventoDao fd = new EventoDao();
        fd.create(f);
        readJTable();

        this.jComboBoxTipo.setToolTipText("");
        this.jTextFieldNome.setText("");
        this.jFormattedTextFieldData.setText("");
        this.jFormattedTextFieldHora.setText("");
        this.jComboBoxDisciplina.setToolTipText("");
        this.jComboBoxFrequencia.setToolTipText("");
        this.jTextFieldAssunto.setText("");

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableCadastroEvento.getSelectedRow() != -1) {

            Evento f = new Evento("", "", "", "", 0, "", "", "");
            EventoDao dao = new EventoDao();

            f.setId((int) jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 0));

            dao.delete(f);
            readJTable();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if (jTableCadastroEvento.getSelectedRow() != -1) {
 Disciplina disciplina = (Disciplina) jComboBoxDisciplina.getSelectedItem();
            Evento f = new Evento((String) jComboBoxTipo.getSelectedItem(), jTextFieldNome.getText(), jFormattedTextFieldData.getText(), jFormattedTextFieldHora.getText(), disciplina.getId(), (String) jComboBoxFrequencia.getSelectedItem(), (String) jComboBoxStatus.getSelectedItem(), jTextFieldAssunto.getText());
            EventoDao dao = new EventoDao();
           
            f.setTipo((String) jComboBoxTipo.getSelectedItem());
            f.setNome(jTextFieldNome.getText());
            f.setData(jFormattedTextFieldData.getText());
            f.setStatus((String) jComboBoxStatus.getSelectedItem());
            f.setIdDisciplina(disciplina.getId());
            f.setHora(jFormattedTextFieldHora.getText());
            f.setFrequencia((String) jComboBoxFrequencia.getSelectedItem());
            f.setAssunto(jTextFieldAssunto.getText());
            f.setId(Integer.parseInt(jTextFieldId.getText()));

            dao.update(f);

            this.jComboBoxTipo.setToolTipText("");
            this.jTextFieldNome.setText("");
            this.jFormattedTextFieldData.setText("");
            this.jFormattedTextFieldHora.setText("");
            this.jComboBoxDisciplina.setToolTipText("");
            this.jComboBoxFrequencia.setToolTipText("");
            this.jComboBoxStatus.setToolTipText("");
            this.jTextFieldAssunto.setText("");

            readJTable();
        } else {
            JOptionPane.showMessageDialog(this, "selecione uma linha para atualizar");
        }

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jComboBoxDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDisciplinaActionPerformed

    private void jTableCadastroEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroEventoMouseClicked
        if (jTableCadastroEvento.getSelectedRow() != -1) {
            jTextFieldId.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 0).toString());
            jComboBoxTipo.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 1).toString());
            jTextFieldNome.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 2).toString());
            jFormattedTextFieldData.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 3).toString());
            jFormattedTextFieldHora.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 4).toString());
            jComboBoxFrequencia.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 5).toString());
            jComboBoxDisciplina.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 6).toString());
            jComboBoxStatus.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 7).toString());
            jTextFieldAssunto.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 8).toString());

        }

    }//GEN-LAST:event_jTableCadastroEventoMouseClicked

    private void jTableCadastroEventoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCadastroEventoKeyReleased
        if (jTableCadastroEvento.getSelectedRow() != -1) {
            jTextFieldId.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 0).toString());
            jComboBoxTipo.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 1).toString());
            jTextFieldNome.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 2).toString());
            jFormattedTextFieldData.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 3).toString());
            jFormattedTextFieldHora.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 4).toString());
            jComboBoxFrequencia.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 5).toString());
            jComboBoxDisciplina.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 6).toString());
            jComboBoxStatus.setToolTipText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 7).toString());
            jTextFieldAssunto.setText(jTableCadastroEvento.getValueAt(jTableCadastroEvento.getSelectedRow(), 8).toString());
        }
    }//GEN-LAST:event_jTableCadastroEventoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<Object> jComboBoxDisciplina;
    private javax.swing.JComboBox<String> jComboBoxFrequencia;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroEvento;
    private javax.swing.JTextField jTextFieldAssunto;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
